# Generated by Django 5.2.17 on 2026-08-10 13:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("STUDENT", "Student"),
                            ("TUTOR", "Tutor"),
                        ],
                        default="STUDENT",
                        max_length=12,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("nickname", models.CharField(blank=True, max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+[1-9]\\d{6,14}$",
                                "Use an international number, e.g. +61412345678.",
                            )
                        ],
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+[1-9]\\d{6,14}$",
                                "Use an international number, e.g. +61412345678.",
                            )
                        ],
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=100),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REJECTED", "Rejected"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "timezone",
                    models.CharField(default="Australia/Sydney", max_length=64),
                ),
                (
                    "availability",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"MONDAY":["09:00","10:00"]}',
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("IN_PERSON", "In person"), ("ONLINE", "Online")],
                        default="ONLINE",
                        max_length=12,
                    ),
                ),
                (
                    "address",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"line1":"", "suburb":"", "state":"", "postcode":"", "country":""}',
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=100)),
                ("same_gender_pairing_required", models.BooleanField(default=False)),
                (
                    "qualitative_assessment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                            ("OUTSTANDING", "Outstanding"),
                        ],
                        max_length=12,
                    ),
                ),
                ("national_background", models.CharField(blank=True, max_length=255)),
                ("ethnic_background", models.CharField(blank=True, max_length=255)),
                ("religious_background", models.CharField(blank=True, max_length=255)),
                ("job_study_category", models.CharField(blank=True, max_length=255)),
                ("current_profession", models.CharField(blank=True, max_length=255)),
                ("hobbies_interests", models.TextField(blank=True)),
                ("reference_check_conducted", models.BooleanField(default=False)),
                ("referee_name", models.CharField(blank=True, max_length=255)),
                ("referee_relationship", models.CharField(blank=True, max_length=255)),
                ("referee_contact", models.CharField(blank=True, max_length=255)),
                ("pathway_to_program", models.CharField(blank=True, max_length=255)),
                ("assessor", models.CharField(blank=True, max_length=255)),
                ("matcher", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "english_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=2,
                    ),
                ),
                ("linguistic_background", models.CharField(blank=True, max_length=255)),
                ("intended_profession", models.CharField(blank=True, max_length=255)),
                ("refugee_asylum_assessment", models.TextField(blank=True)),
                (
                    "interview_conducted",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONDUCTED", "Conducted"),
                            ("FOLLOW_UP", "Follow up required"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to="portal.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "session_time",
                    models.JSONField(
                        default=dict, help_text='{"day":"MONDAY", "time":"10:00"}'
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("STOPPED", "Stopped")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pairings",
                        to="portal.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutoringSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_notes", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pairing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="portal.pairing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "other_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"language":"Arabic","level":"B2"}]',
                    ),
                ),
                ("approved_to_tutor", models.BooleanField(default=False)),
                ("capacity", models.PositiveSmallIntegerField(default=1)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_profile",
                        to="portal.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pairing",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pairings",
                to="portal.tutorprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="pairing",
            constraint=models.UniqueConstraint(
                fields=("tutor", "student"), name="unique_pairing"
            ),
        ),
    ]
