# Generated by Django 5.0 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("portal", "0003_blacklist_status")]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="wwcc_provided",
            field=models.BooleanField(default=False),
        ),
    ]
